openapi: 3.0.1
info: 
  title: Cidade
  description: API para 
  version: 0.0.1

host: ""
paths:
  /api/states:
    get:
      summary: Seleciona todas as cidades cadastradas.
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  descricao:
                    type: string
        400:
          description: Cidade não encontrada
           content:
            application/json:
              example: "Not Found"
    post:
      summary: Cadastra uma nova cidade.

      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            example:
              nome: Pernambuco
              regiao: Nordeste
              populacao: 92780000000
              capital: recife
              area: 98312
  /api/states/{id}:
  get:
      summary: Filtra cidades pela regiao, por area, ou por população.
      description:
        É necessário a declaração do número da página que será acessada,
        juntamente com a quantidade de cidades que deverão aparecer por página.
        Para ordenação de itens, o nome do parâmetro, pelo qual se quer ordenar, 
        deve ser chamado.
      parameters:
        - name: pag
          in: path
          description: número da pagina
          type: integer
          required: true
        - name: qtd
          in: path
          description: Quantidade de itens que deverão aparecer por página
          type: integer
          required: true
        - name: ordenacao
          in: path
          description: nome do parâmetro a ser utilizado para ordenar
          type: String
          required: false
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: object
    put:
      summary: Atualização de uma cidade
      responses: 
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  descricao:
                    type: string
        400:
          description: Cidade não encontrada
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  descricao:
                    type: string
    delete:
      summary: Exclusão de uma cidade
        400:
          description: Entidade não encontrada
          content:
            application/json:
              example: "Not Found"